# Generated by Django 3.2.8 on 2021-10-10 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='products_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
